server:
  port: 10010
spring:
  application:
    name: config1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
